//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.22 at 02:13:30 AM CDT 
//


package org.store.publications.onix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ExtentType"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ExtentValue" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ExtentValueRoman" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ExtentUnit"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.editeur.org/onix/3.0/reference}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Extent"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="extent"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extentType",
    "extentValue",
    "extentValueRoman",
    "extentUnit"
})
@XmlRootElement(name = "Extent")
public class Extent {

    @XmlElement(name = "ExtentType", required = true)
    protected ExtentType extentType;
    @XmlElement(name = "ExtentValue")
    protected ExtentValue extentValue;
    @XmlElement(name = "ExtentValueRoman")
    protected ExtentValueRoman extentValueRoman;
    @XmlElement(name = "ExtentUnit", required = true)
    protected ExtentUnit extentUnit;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute
    protected String datestamp;
    @XmlAttribute
    protected String sourcetype;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the extentType property.
     * 
     * @return
     *     possible object is
     *     {@link ExtentType }
     *     
     */
    public ExtentType getExtentType() {
        return extentType;
    }

    /**
     * Sets the value of the extentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtentType }
     *     
     */
    public void setExtentType(ExtentType value) {
        this.extentType = value;
    }

    /**
     * Gets the value of the extentValue property.
     * 
     * @return
     *     possible object is
     *     {@link ExtentValue }
     *     
     */
    public ExtentValue getExtentValue() {
        return extentValue;
    }

    /**
     * Sets the value of the extentValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtentValue }
     *     
     */
    public void setExtentValue(ExtentValue value) {
        this.extentValue = value;
    }

    /**
     * Gets the value of the extentValueRoman property.
     * 
     * @return
     *     possible object is
     *     {@link ExtentValueRoman }
     *     
     */
    public ExtentValueRoman getExtentValueRoman() {
        return extentValueRoman;
    }

    /**
     * Sets the value of the extentValueRoman property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtentValueRoman }
     *     
     */
    public void setExtentValueRoman(ExtentValueRoman value) {
        this.extentValueRoman = value;
    }

    /**
     * Gets the value of the extentUnit property.
     * 
     * @return
     *     possible object is
     *     {@link ExtentUnit }
     *     
     */
    public ExtentUnit getExtentUnit() {
        return extentUnit;
    }

    /**
     * Sets the value of the extentUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtentUnit }
     *     
     */
    public void setExtentUnit(ExtentUnit value) {
        this.extentUnit = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
