//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.22 at 02:13:30 AM CDT 
//


package org.store.publications.onix;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List178.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List178">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A103"/>
 *     &lt;enumeration value="A104"/>
 *     &lt;enumeration value="A105"/>
 *     &lt;enumeration value="A106"/>
 *     &lt;enumeration value="A107"/>
 *     &lt;enumeration value="D101"/>
 *     &lt;enumeration value="D102"/>
 *     &lt;enumeration value="D103"/>
 *     &lt;enumeration value="D104"/>
 *     &lt;enumeration value="D105"/>
 *     &lt;enumeration value="D106"/>
 *     &lt;enumeration value="D107"/>
 *     &lt;enumeration value="D401"/>
 *     &lt;enumeration value="D501"/>
 *     &lt;enumeration value="D502"/>
 *     &lt;enumeration value="D503"/>
 *     &lt;enumeration value="D504"/>
 *     &lt;enumeration value="E101"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "List178")
@XmlEnum
public enum List178 {

    @XmlEnumValue("A103")
    A_103("A103"),
    @XmlEnumValue("A104")
    A_104("A104"),
    @XmlEnumValue("A105")
    A_105("A105"),

    /**
     * Windows Media Audio format.
     * 
     */
    @XmlEnumValue("A106")
    A_106("A106"),

    /**
     * Advanced Audio Coding format.
     * 
     */
    @XmlEnumValue("A107")
    A_107("A107"),
    @XmlEnumValue("D101")
    D_101("D101"),
    @XmlEnumValue("D102")
    D_102("D102"),
    @XmlEnumValue("D103")
    D_103("D103"),

    /**
     * Windows Media Video format.
     * 
     */
    @XmlEnumValue("D104")
    D_104("D104"),
    @XmlEnumValue("D105")
    D_105("D105"),

    /**
     * Flash Video.
     * 
     */
    @XmlEnumValue("D106")
    D_106("D106"),

    /**
     * ShockWave.
     * 
     */
    @XmlEnumValue("D107")
    D_107("D107"),
    @XmlEnumValue("D401")
    D_401("D401"),
    @XmlEnumValue("D501")
    D_501("D501"),
    @XmlEnumValue("D502")
    D_502("D502"),
    @XmlEnumValue("D503")
    D_503("D503"),
    @XmlEnumValue("D504")
    D_504("D504"),

    /**
     * The Open Publication Structure / OPS Container Format standard of the International Digital Publishing Forum (IDPF) [File extension .epub].
     * 
     */
    @XmlEnumValue("E101")
    E_101("E101");
    private final String value;

    List178(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List178 fromValue(String v) {
        for (List178 c: List178 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
