//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.22 at 02:13:30 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.editeur.org/onix/3.0/reference", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.store.publications.onix;
