//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.22 at 02:13:30 AM CDT 
//


package org.store.publications.onix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ProductFormFeatureType"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ProductFormFeatureValue" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ProductFormFeatureDescription" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.editeur.org/onix/3.0/reference}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="ProductFormFeature"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="productformfeature"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productFormFeatureType",
    "productFormFeatureValue",
    "productFormFeatureDescription"
})
@XmlRootElement(name = "ProductFormFeature")
public class ProductFormFeature {

    @XmlElement(name = "ProductFormFeatureType", required = true)
    protected ProductFormFeatureType productFormFeatureType;
    @XmlElement(name = "ProductFormFeatureValue")
    protected ProductFormFeatureValue productFormFeatureValue;
    @XmlElement(name = "ProductFormFeatureDescription")
    protected ProductFormFeatureDescription productFormFeatureDescription;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute
    protected String datestamp;
    @XmlAttribute
    protected String sourcetype;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the productFormFeatureType property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFormFeatureType }
     *     
     */
    public ProductFormFeatureType getProductFormFeatureType() {
        return productFormFeatureType;
    }

    /**
     * Sets the value of the productFormFeatureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFormFeatureType }
     *     
     */
    public void setProductFormFeatureType(ProductFormFeatureType value) {
        this.productFormFeatureType = value;
    }

    /**
     * Gets the value of the productFormFeatureValue property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFormFeatureValue }
     *     
     */
    public ProductFormFeatureValue getProductFormFeatureValue() {
        return productFormFeatureValue;
    }

    /**
     * Sets the value of the productFormFeatureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFormFeatureValue }
     *     
     */
    public void setProductFormFeatureValue(ProductFormFeatureValue value) {
        this.productFormFeatureValue = value;
    }

    /**
     * Gets the value of the productFormFeatureDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFormFeatureDescription }
     *     
     */
    public ProductFormFeatureDescription getProductFormFeatureDescription() {
        return productFormFeatureDescription;
    }

    /**
     * Sets the value of the productFormFeatureDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFormFeatureDescription }
     *     
     */
    public void setProductFormFeatureDescription(ProductFormFeatureDescription value) {
        this.productFormFeatureDescription = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
