//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.22 at 02:13:30 AM CDT 
//


package org.store.publications.onix;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}PrimaryPart" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ProductIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ProductForm"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ProductFormDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ProductFormFeature" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ProductFormDescription" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ProductContentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}NumberOfItemsOfThisForm" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}NumberOfCopies" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}CountryOfManufacture" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.editeur.org/onix/3.0/reference}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="ProductPart"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="productpart"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "primaryPart",
    "productIdentifier",
    "productForm",
    "productFormDetail",
    "productFormFeature",
    "productFormDescription",
    "productContentType",
    "numberOfItemsOfThisForm",
    "numberOfCopies",
    "countryOfManufacture"
})
@XmlRootElement(name = "ProductPart")
public class ProductPart {

    @XmlElement(name = "PrimaryPart")
    protected PrimaryPart primaryPart;
    @XmlElement(name = "ProductIdentifier")
    protected List<ProductIdentifier> productIdentifier;
    @XmlElement(name = "ProductForm", required = true)
    protected ProductForm productForm;
    @XmlElement(name = "ProductFormDetail")
    protected List<ProductFormDetail> productFormDetail;
    @XmlElement(name = "ProductFormFeature")
    protected List<ProductFormFeature> productFormFeature;
    @XmlElement(name = "ProductFormDescription")
    protected ProductFormDescription productFormDescription;
    @XmlElement(name = "ProductContentType")
    protected List<ProductContentType> productContentType;
    @XmlElement(name = "NumberOfItemsOfThisForm")
    protected NumberOfItemsOfThisForm numberOfItemsOfThisForm;
    @XmlElement(name = "NumberOfCopies")
    protected NumberOfCopies numberOfCopies;
    @XmlElement(name = "CountryOfManufacture")
    protected CountryOfManufacture countryOfManufacture;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute
    protected String datestamp;
    @XmlAttribute
    protected String sourcetype;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the primaryPart property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryPart }
     *     
     */
    public PrimaryPart getPrimaryPart() {
        return primaryPart;
    }

    /**
     * Sets the value of the primaryPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryPart }
     *     
     */
    public void setPrimaryPart(PrimaryPart value) {
        this.primaryPart = value;
    }

    /**
     * Gets the value of the productIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductIdentifier }
     * 
     * 
     */
    public List<ProductIdentifier> getProductIdentifier() {
        if (productIdentifier == null) {
            productIdentifier = new ArrayList<ProductIdentifier>();
        }
        return this.productIdentifier;
    }

    /**
     * Gets the value of the productForm property.
     * 
     * @return
     *     possible object is
     *     {@link ProductForm }
     *     
     */
    public ProductForm getProductForm() {
        return productForm;
    }

    /**
     * Sets the value of the productForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductForm }
     *     
     */
    public void setProductForm(ProductForm value) {
        this.productForm = value;
    }

    /**
     * Gets the value of the productFormDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productFormDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductFormDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductFormDetail }
     * 
     * 
     */
    public List<ProductFormDetail> getProductFormDetail() {
        if (productFormDetail == null) {
            productFormDetail = new ArrayList<ProductFormDetail>();
        }
        return this.productFormDetail;
    }

    /**
     * Gets the value of the productFormFeature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productFormFeature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductFormFeature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductFormFeature }
     * 
     * 
     */
    public List<ProductFormFeature> getProductFormFeature() {
        if (productFormFeature == null) {
            productFormFeature = new ArrayList<ProductFormFeature>();
        }
        return this.productFormFeature;
    }

    /**
     * Gets the value of the productFormDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFormDescription }
     *     
     */
    public ProductFormDescription getProductFormDescription() {
        return productFormDescription;
    }

    /**
     * Sets the value of the productFormDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFormDescription }
     *     
     */
    public void setProductFormDescription(ProductFormDescription value) {
        this.productFormDescription = value;
    }

    /**
     * Gets the value of the productContentType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productContentType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductContentType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductContentType }
     * 
     * 
     */
    public List<ProductContentType> getProductContentType() {
        if (productContentType == null) {
            productContentType = new ArrayList<ProductContentType>();
        }
        return this.productContentType;
    }

    /**
     * Gets the value of the numberOfItemsOfThisForm property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfItemsOfThisForm }
     *     
     */
    public NumberOfItemsOfThisForm getNumberOfItemsOfThisForm() {
        return numberOfItemsOfThisForm;
    }

    /**
     * Sets the value of the numberOfItemsOfThisForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfItemsOfThisForm }
     *     
     */
    public void setNumberOfItemsOfThisForm(NumberOfItemsOfThisForm value) {
        this.numberOfItemsOfThisForm = value;
    }

    /**
     * Gets the value of the numberOfCopies property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfCopies }
     *     
     */
    public NumberOfCopies getNumberOfCopies() {
        return numberOfCopies;
    }

    /**
     * Sets the value of the numberOfCopies property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfCopies }
     *     
     */
    public void setNumberOfCopies(NumberOfCopies value) {
        this.numberOfCopies = value;
    }

    /**
     * Gets the value of the countryOfManufacture property.
     * 
     * @return
     *     possible object is
     *     {@link CountryOfManufacture }
     *     
     */
    public CountryOfManufacture getCountryOfManufacture() {
        return countryOfManufacture;
    }

    /**
     * Sets the value of the countryOfManufacture property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryOfManufacture }
     *     
     */
    public void setCountryOfManufacture(CountryOfManufacture value) {
        this.countryOfManufacture = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
