//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.22 at 02:13:30 AM CDT 
//


package org.store.publications.onix;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.editeur.org/onix/3.0/reference}gp.publisher"/>
 *         &lt;group ref="{http://www.editeur.org/onix/3.0/reference}gp.publishing_status"/>
 *         &lt;group ref="{http://www.editeur.org/onix/3.0/reference}gp.rights_restrictions"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.editeur.org/onix/3.0/reference}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="PublishingDetail"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="publishingdetail"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imprint",
    "publisher",
    "cityOfPublication",
    "countryOfPublication",
    "publishingStatus",
    "publishingStatusNote",
    "publishingDate",
    "latestReprintNumber",
    "copyrightStatement",
    "salesRights",
    "rowSalesRightsType",
    "salesRestriction"
})
@XmlRootElement(name = "PublishingDetail")
public class PublishingDetail {

    @XmlElement(name = "Imprint")
    protected List<Imprint> imprint;
    @XmlElement(name = "Publisher")
    protected List<Publisher> publisher;
    @XmlElement(name = "CityOfPublication")
    protected List<CityOfPublication> cityOfPublication;
    @XmlElement(name = "CountryOfPublication")
    protected CountryOfPublication countryOfPublication;
    @XmlElement(name = "PublishingStatus")
    protected PublishingStatus publishingStatus;
    @XmlElement(name = "PublishingStatusNote")
    protected PublishingStatusNote publishingStatusNote;
    @XmlElement(name = "PublishingDate")
    protected List<PublishingDate> publishingDate;
    @XmlElement(name = "LatestReprintNumber")
    protected LatestReprintNumber latestReprintNumber;
    @XmlElement(name = "CopyrightStatement")
    protected List<CopyrightStatement> copyrightStatement;
    @XmlElement(name = "SalesRights")
    protected List<SalesRights> salesRights;
    @XmlElement(name = "ROWSalesRightsType")
    protected ROWSalesRightsType rowSalesRightsType;
    @XmlElement(name = "SalesRestriction")
    protected List<SalesRestriction> salesRestriction;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute
    protected String datestamp;
    @XmlAttribute
    protected String sourcetype;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the imprint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imprint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImprint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Imprint }
     * 
     * 
     */
    public List<Imprint> getImprint() {
        if (imprint == null) {
            imprint = new ArrayList<Imprint>();
        }
        return this.imprint;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publisher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublisher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Publisher }
     * 
     * 
     */
    public List<Publisher> getPublisher() {
        if (publisher == null) {
            publisher = new ArrayList<Publisher>();
        }
        return this.publisher;
    }

    /**
     * Gets the value of the cityOfPublication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cityOfPublication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCityOfPublication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CityOfPublication }
     * 
     * 
     */
    public List<CityOfPublication> getCityOfPublication() {
        if (cityOfPublication == null) {
            cityOfPublication = new ArrayList<CityOfPublication>();
        }
        return this.cityOfPublication;
    }

    /**
     * Gets the value of the countryOfPublication property.
     * 
     * @return
     *     possible object is
     *     {@link CountryOfPublication }
     *     
     */
    public CountryOfPublication getCountryOfPublication() {
        return countryOfPublication;
    }

    /**
     * Sets the value of the countryOfPublication property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryOfPublication }
     *     
     */
    public void setCountryOfPublication(CountryOfPublication value) {
        this.countryOfPublication = value;
    }

    /**
     * Gets the value of the publishingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PublishingStatus }
     *     
     */
    public PublishingStatus getPublishingStatus() {
        return publishingStatus;
    }

    /**
     * Sets the value of the publishingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishingStatus }
     *     
     */
    public void setPublishingStatus(PublishingStatus value) {
        this.publishingStatus = value;
    }

    /**
     * Gets the value of the publishingStatusNote property.
     * 
     * @return
     *     possible object is
     *     {@link PublishingStatusNote }
     *     
     */
    public PublishingStatusNote getPublishingStatusNote() {
        return publishingStatusNote;
    }

    /**
     * Sets the value of the publishingStatusNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishingStatusNote }
     *     
     */
    public void setPublishingStatusNote(PublishingStatusNote value) {
        this.publishingStatusNote = value;
    }

    /**
     * Gets the value of the publishingDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publishingDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublishingDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublishingDate }
     * 
     * 
     */
    public List<PublishingDate> getPublishingDate() {
        if (publishingDate == null) {
            publishingDate = new ArrayList<PublishingDate>();
        }
        return this.publishingDate;
    }

    /**
     * Gets the value of the latestReprintNumber property.
     * 
     * @return
     *     possible object is
     *     {@link LatestReprintNumber }
     *     
     */
    public LatestReprintNumber getLatestReprintNumber() {
        return latestReprintNumber;
    }

    /**
     * Sets the value of the latestReprintNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link LatestReprintNumber }
     *     
     */
    public void setLatestReprintNumber(LatestReprintNumber value) {
        this.latestReprintNumber = value;
    }

    /**
     * Gets the value of the copyrightStatement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the copyrightStatement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCopyrightStatement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CopyrightStatement }
     * 
     * 
     */
    public List<CopyrightStatement> getCopyrightStatement() {
        if (copyrightStatement == null) {
            copyrightStatement = new ArrayList<CopyrightStatement>();
        }
        return this.copyrightStatement;
    }

    /**
     * Gets the value of the salesRights property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the salesRights property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSalesRights().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SalesRights }
     * 
     * 
     */
    public List<SalesRights> getSalesRights() {
        if (salesRights == null) {
            salesRights = new ArrayList<SalesRights>();
        }
        return this.salesRights;
    }

    /**
     * Gets the value of the rowSalesRightsType property.
     * 
     * @return
     *     possible object is
     *     {@link ROWSalesRightsType }
     *     
     */
    public ROWSalesRightsType getROWSalesRightsType() {
        return rowSalesRightsType;
    }

    /**
     * Sets the value of the rowSalesRightsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROWSalesRightsType }
     *     
     */
    public void setROWSalesRightsType(ROWSalesRightsType value) {
        this.rowSalesRightsType = value;
    }

    /**
     * Gets the value of the salesRestriction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the salesRestriction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSalesRestriction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SalesRestriction }
     * 
     * 
     */
    public List<SalesRestriction> getSalesRestriction() {
        if (salesRestriction == null) {
            salesRestriction = new ArrayList<SalesRestriction>();
        }
        return this.salesRestriction;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
