//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.22 at 02:13:30 AM CDT 
//


package org.store.publications.onix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ReligiousTextFeatureType"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ReligiousTextFeatureCode"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}ReligiousTextFeatureDescription" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.editeur.org/onix/3.0/reference}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="ReligiousTextFeature"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="religioustextfeature"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "religiousTextFeatureType",
    "religiousTextFeatureCode",
    "religiousTextFeatureDescription"
})
@XmlRootElement(name = "ReligiousTextFeature")
public class ReligiousTextFeature {

    @XmlElement(name = "ReligiousTextFeatureType", required = true)
    protected ReligiousTextFeatureType religiousTextFeatureType;
    @XmlElement(name = "ReligiousTextFeatureCode", required = true)
    protected ReligiousTextFeatureCode religiousTextFeatureCode;
    @XmlElement(name = "ReligiousTextFeatureDescription")
    protected ReligiousTextFeatureDescription religiousTextFeatureDescription;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute
    protected String datestamp;
    @XmlAttribute
    protected String sourcetype;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the religiousTextFeatureType property.
     * 
     * @return
     *     possible object is
     *     {@link ReligiousTextFeatureType }
     *     
     */
    public ReligiousTextFeatureType getReligiousTextFeatureType() {
        return religiousTextFeatureType;
    }

    /**
     * Sets the value of the religiousTextFeatureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReligiousTextFeatureType }
     *     
     */
    public void setReligiousTextFeatureType(ReligiousTextFeatureType value) {
        this.religiousTextFeatureType = value;
    }

    /**
     * Gets the value of the religiousTextFeatureCode property.
     * 
     * @return
     *     possible object is
     *     {@link ReligiousTextFeatureCode }
     *     
     */
    public ReligiousTextFeatureCode getReligiousTextFeatureCode() {
        return religiousTextFeatureCode;
    }

    /**
     * Sets the value of the religiousTextFeatureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReligiousTextFeatureCode }
     *     
     */
    public void setReligiousTextFeatureCode(ReligiousTextFeatureCode value) {
        this.religiousTextFeatureCode = value;
    }

    /**
     * Gets the value of the religiousTextFeatureDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ReligiousTextFeatureDescription }
     *     
     */
    public ReligiousTextFeatureDescription getReligiousTextFeatureDescription() {
        return religiousTextFeatureDescription;
    }

    /**
     * Sets the value of the religiousTextFeatureDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReligiousTextFeatureDescription }
     *     
     */
    public void setReligiousTextFeatureDescription(ReligiousTextFeatureDescription value) {
        this.religiousTextFeatureDescription = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
