//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.22 at 02:13:30 AM CDT 
//


package org.store.publications.onix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}MainSubject" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}SubjectSchemeIdentifier"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}SubjectSchemeName" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}SubjectSchemeVersion" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}SubjectCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}SubjectHeadingText" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.editeur.org/onix/3.0/reference}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Subject"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="subject"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mainSubject",
    "subjectSchemeIdentifier",
    "subjectSchemeName",
    "subjectSchemeVersion",
    "subjectCode",
    "subjectHeadingText"
})
@XmlRootElement(name = "Subject")
public class Subject {

    @XmlElement(name = "MainSubject")
    protected MainSubject mainSubject;
    @XmlElement(name = "SubjectSchemeIdentifier", required = true)
    protected SubjectSchemeIdentifier subjectSchemeIdentifier;
    @XmlElement(name = "SubjectSchemeName")
    protected SubjectSchemeName subjectSchemeName;
    @XmlElement(name = "SubjectSchemeVersion")
    protected SubjectSchemeVersion subjectSchemeVersion;
    @XmlElement(name = "SubjectCode")
    protected SubjectCode subjectCode;
    @XmlElement(name = "SubjectHeadingText")
    protected SubjectHeadingText subjectHeadingText;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute
    protected String datestamp;
    @XmlAttribute
    protected String sourcetype;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the mainSubject property.
     * 
     * @return
     *     possible object is
     *     {@link MainSubject }
     *     
     */
    public MainSubject getMainSubject() {
        return mainSubject;
    }

    /**
     * Sets the value of the mainSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link MainSubject }
     *     
     */
    public void setMainSubject(MainSubject value) {
        this.mainSubject = value;
    }

    /**
     * Gets the value of the subjectSchemeIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectSchemeIdentifier }
     *     
     */
    public SubjectSchemeIdentifier getSubjectSchemeIdentifier() {
        return subjectSchemeIdentifier;
    }

    /**
     * Sets the value of the subjectSchemeIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectSchemeIdentifier }
     *     
     */
    public void setSubjectSchemeIdentifier(SubjectSchemeIdentifier value) {
        this.subjectSchemeIdentifier = value;
    }

    /**
     * Gets the value of the subjectSchemeName property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectSchemeName }
     *     
     */
    public SubjectSchemeName getSubjectSchemeName() {
        return subjectSchemeName;
    }

    /**
     * Sets the value of the subjectSchemeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectSchemeName }
     *     
     */
    public void setSubjectSchemeName(SubjectSchemeName value) {
        this.subjectSchemeName = value;
    }

    /**
     * Gets the value of the subjectSchemeVersion property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectSchemeVersion }
     *     
     */
    public SubjectSchemeVersion getSubjectSchemeVersion() {
        return subjectSchemeVersion;
    }

    /**
     * Sets the value of the subjectSchemeVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectSchemeVersion }
     *     
     */
    public void setSubjectSchemeVersion(SubjectSchemeVersion value) {
        this.subjectSchemeVersion = value;
    }

    /**
     * Gets the value of the subjectCode property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectCode }
     *     
     */
    public SubjectCode getSubjectCode() {
        return subjectCode;
    }

    /**
     * Sets the value of the subjectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectCode }
     *     
     */
    public void setSubjectCode(SubjectCode value) {
        this.subjectCode = value;
    }

    /**
     * Gets the value of the subjectHeadingText property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectHeadingText }
     *     
     */
    public SubjectHeadingText getSubjectHeadingText() {
        return subjectHeadingText;
    }

    /**
     * Sets the value of the subjectHeadingText property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectHeadingText }
     *     
     */
    public void setSubjectHeadingText(SubjectHeadingText value) {
        this.subjectHeadingText = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
