//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.22 at 02:13:30 AM CDT 
//


package org.store.publications.onix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}CountriesIncluded" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}RegionsIncluded" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}CountriesExcluded" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}RegionsExcluded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.editeur.org/onix/3.0/reference}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Territory"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="territory"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "countriesIncluded",
    "regionsIncluded",
    "countriesExcluded",
    "regionsExcluded"
})
@XmlRootElement(name = "Territory")
public class Territory {

    @XmlElement(name = "CountriesIncluded")
    protected CountriesIncluded countriesIncluded;
    @XmlElement(name = "RegionsIncluded")
    protected RegionsIncluded regionsIncluded;
    @XmlElement(name = "CountriesExcluded")
    protected CountriesExcluded countriesExcluded;
    @XmlElement(name = "RegionsExcluded")
    protected RegionsExcluded regionsExcluded;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute
    protected String datestamp;
    @XmlAttribute
    protected String sourcetype;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the countriesIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link CountriesIncluded }
     *     
     */
    public CountriesIncluded getCountriesIncluded() {
        return countriesIncluded;
    }

    /**
     * Sets the value of the countriesIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountriesIncluded }
     *     
     */
    public void setCountriesIncluded(CountriesIncluded value) {
        this.countriesIncluded = value;
    }

    /**
     * Gets the value of the regionsIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link RegionsIncluded }
     *     
     */
    public RegionsIncluded getRegionsIncluded() {
        return regionsIncluded;
    }

    /**
     * Sets the value of the regionsIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionsIncluded }
     *     
     */
    public void setRegionsIncluded(RegionsIncluded value) {
        this.regionsIncluded = value;
    }

    /**
     * Gets the value of the countriesExcluded property.
     * 
     * @return
     *     possible object is
     *     {@link CountriesExcluded }
     *     
     */
    public CountriesExcluded getCountriesExcluded() {
        return countriesExcluded;
    }

    /**
     * Sets the value of the countriesExcluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountriesExcluded }
     *     
     */
    public void setCountriesExcluded(CountriesExcluded value) {
        this.countriesExcluded = value;
    }

    /**
     * Gets the value of the regionsExcluded property.
     * 
     * @return
     *     possible object is
     *     {@link RegionsExcluded }
     *     
     */
    public RegionsExcluded getRegionsExcluded() {
        return regionsExcluded;
    }

    /**
     * Sets the value of the regionsExcluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionsExcluded }
     *     
     */
    public void setRegionsExcluded(RegionsExcluded value) {
        this.regionsExcluded = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
