//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.22 at 02:13:30 AM CDT 
//


package org.store.publications.onix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}TitleElementLevel"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}PartNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}YearOfAnnual" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}TitleText" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}TitlePrefix" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}TitleWithoutPrefix" minOccurs="0"/>
 *         &lt;element ref="{http://www.editeur.org/onix/3.0/reference}Subtitle" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.editeur.org/onix/3.0/reference}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="TitleElement"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="titleelement"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titleElementLevel",
    "partNumber",
    "yearOfAnnual",
    "titleText",
    "titlePrefix",
    "titleWithoutPrefix",
    "subtitle"
})
@XmlRootElement(name = "TitleElement")
public class TitleElement {

    @XmlElement(name = "TitleElementLevel", required = true)
    protected TitleElementLevel titleElementLevel;
    @XmlElement(name = "PartNumber")
    protected PartNumber partNumber;
    @XmlElement(name = "YearOfAnnual")
    protected YearOfAnnual yearOfAnnual;
    @XmlElement(name = "TitleText")
    protected TitleText titleText;
    @XmlElement(name = "TitlePrefix")
    protected TitlePrefix titlePrefix;
    @XmlElement(name = "TitleWithoutPrefix")
    protected TitleWithoutPrefix titleWithoutPrefix;
    @XmlElement(name = "Subtitle")
    protected Subtitle subtitle;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute
    protected String datestamp;
    @XmlAttribute
    protected String sourcetype;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the titleElementLevel property.
     * 
     * @return
     *     possible object is
     *     {@link TitleElementLevel }
     *     
     */
    public TitleElementLevel getTitleElementLevel() {
        return titleElementLevel;
    }

    /**
     * Sets the value of the titleElementLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleElementLevel }
     *     
     */
    public void setTitleElementLevel(TitleElementLevel value) {
        this.titleElementLevel = value;
    }

    /**
     * Gets the value of the partNumber property.
     * 
     * @return
     *     possible object is
     *     {@link PartNumber }
     *     
     */
    public PartNumber getPartNumber() {
        return partNumber;
    }

    /**
     * Sets the value of the partNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartNumber }
     *     
     */
    public void setPartNumber(PartNumber value) {
        this.partNumber = value;
    }

    /**
     * Gets the value of the yearOfAnnual property.
     * 
     * @return
     *     possible object is
     *     {@link YearOfAnnual }
     *     
     */
    public YearOfAnnual getYearOfAnnual() {
        return yearOfAnnual;
    }

    /**
     * Sets the value of the yearOfAnnual property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearOfAnnual }
     *     
     */
    public void setYearOfAnnual(YearOfAnnual value) {
        this.yearOfAnnual = value;
    }

    /**
     * Gets the value of the titleText property.
     * 
     * @return
     *     possible object is
     *     {@link TitleText }
     *     
     */
    public TitleText getTitleText() {
        return titleText;
    }

    /**
     * Sets the value of the titleText property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleText }
     *     
     */
    public void setTitleText(TitleText value) {
        this.titleText = value;
    }

    /**
     * Gets the value of the titlePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link TitlePrefix }
     *     
     */
    public TitlePrefix getTitlePrefix() {
        return titlePrefix;
    }

    /**
     * Sets the value of the titlePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitlePrefix }
     *     
     */
    public void setTitlePrefix(TitlePrefix value) {
        this.titlePrefix = value;
    }

    /**
     * Gets the value of the titleWithoutPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link TitleWithoutPrefix }
     *     
     */
    public TitleWithoutPrefix getTitleWithoutPrefix() {
        return titleWithoutPrefix;
    }

    /**
     * Sets the value of the titleWithoutPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleWithoutPrefix }
     *     
     */
    public void setTitleWithoutPrefix(TitleWithoutPrefix value) {
        this.titleWithoutPrefix = value;
    }

    /**
     * Gets the value of the subtitle property.
     * 
     * @return
     *     possible object is
     *     {@link Subtitle }
     *     
     */
    public Subtitle getSubtitle() {
        return subtitle;
    }

    /**
     * Sets the value of the subtitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subtitle }
     *     
     */
    public void setSubtitle(Subtitle value) {
        this.subtitle = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
